/***
 * *PARCEL-BUNDLER
 * CREATE-LIVE-SERVER
 * HMR-HOT MODULE REPLACEMENT
 * FILE WATCHER ALGORITHM
 * SETUP YOUR APP WITH BABEL PLUGIN TO (.babelrc) AUTOMATIC CLEAR CONSOLE.LOG
 * CONSISTENT HASHING ALGORITHM
 * FILE MINIFY
 * HTTPS ON DEVELOPMENT ENVIRONMENT USING NPX PARCEL INDEX.HTML --HTTPS
 * TRANSITIVE DEPENDENCIES
 * AUTOMATIC PIC-UP PORT NUMBER
 * OLDER BROWSERS VERSION SUPPORTS
 * COMPRESSION
 * IMAGE OPTIMIZATION AUTOMATICALLY
 * CACHING WHILE DEVELOPMENT
 * SUPER FAST BUILD ALGORITHM
 * ZERO CONFIG
 * TREE SHAKING - REMOVING UN-WANTED CODE
 *
 * *OTHER IMPORTANT NOTE
 * USE YOUR INDEX.HTML FILE IN THE START AND BUILD COMMAND IN YOUR STARTER SCRIPT
 * REMOVE {main:"App.js"} <<< remove this line from package.json while using parcel
 * ADD type="module" <<<ADD INSIDE YOUR SCRIPT TAG IN INDEX.HTML FILE
 *
 * *OTHER IMPORTANT NOTE
 * ^2.8.2 THIS SIGN USE FOR AUTOMATIC VERSION UPDATE
 * ~2.8.2 THIS SIGN USE FOR PATCH UPDATE
 *  2.8.2 NOT ANY SING THEN YOUR PROJECT WORKING ONLY SPECIFIC VERSION
 * PUSH YOUR PACKAGE-LOCK.JSON FILE TO YOUR GIT REPO SO WHEN WE DEPLOY YOUR APP THEN SERVER KNOW HWT VERSION DO YOU USE IN YOUR PROJECT DON'T DELETE YOUR PACKAGE-LOCK.JSON
 *
 *
 * *OTHER IMPORTANT NOTE
 * READ ABOUT REACT RECONCILIATION
 * READ ABOUT The Diffing Algorithm
 * HOW IT WORKS IN REACT>>>>React.createElement => Object =>HTML(DOM)
 *
 * CREATING BIG HTML STRUCTURE LIKE THIS BUT THIS IS NOT Relevant TO BIG APPLICATION SO WE MOVE TO WRITE YOUR CODE WITH HELP OF JSX
 */
import React from "react";
import ReactDOM from "react-dom/client";
/***
 * * CREATE HTML LIKE STRUCTURE USING React.createElement
 * <div>
      <h1>Heading1</h1>
      <ul>
        <li>list 1</li>
        <li>list 2</li>
        <li>list 2</li>
      </ul>
    </div>
 *  */
//REACT ELEMENT
const container = React.createElement(
    "div",
    {
        id: "container",
        className: "container",
        key: "div",
    },
    "Namaste react"
);
//JSX javascript XML
const heading = <h1 className="container">Heading</h1>
console.log(heading);

const root = ReactDOM.createRoot(document.getElementById("root"));

root.render(heading);
